### ISSUE TITLE
Option[T] fields not handled in a manner consistent with casecodec

### ISSUE THREAD

**Issue by AlecZorab** [alexarchambault/argonaut-shapeless#6]
Argonaut 6.1-M5 vs argonaut-shapeless 0.1.1

```scala

  import argonaut._, Argonaut._
  case class OI(oi: Option[Int])
  val json = Parse.parseOption("{}").get

  locally {
    import argonaut.Shapeless._
    val oi = json.as[OI]
    oi $ println // DecodeResult(-\/((Attempt to decode value on failed cursor.,CursorHistory([*.--\(oi)]))))
  }

  locally {
    implicit val oidecode = casecodec1(OI.apply, OI.unapply)("oi")
    val oi = json.as[OI]
    oi $ println // DecodeResult(\/-(OI(None)))
  }
```

**Comment by alexarchambault** [comment]
Yep, I'd say argonaut-shapeless expects a field `oi` in the JSON and can't find it.

I'm going to have a closer look at how the codecs behave, in particular wrt https://github.com/alexarchambault/argonaut-shapeless/pull/5. Should be very soon, this week hopefully. I'll try to address that at the same time.

**Comment by AlecZorab** [comment]
It boils down to the HCursor on AutoDecodeJsons#21 behaving a little oddly. The cursor comes out as a failure, quite rightly because the key is absent, but substituting in ```val head =  c.get(key.value.name)(headDecode.value).map(field[K](_))``` on line 22 gives a correctly decoded None.

Switching the body of hconsDecodeJson to the following makes the decoding work, but will a) slow the decoding and b) lose you the nice history from the HCursor

```scala
val head =  c.get(key.value.name)(headDecode.value).map(field[K](_))
lazy val tail = c.as(tailDecode.value)
apply2(head, tail)(_ :: _)```

**Comment by alexarchambault** [comment]
https://github.com/alexarchambault/argonaut-shapeless/commit/1dffba998602f8306e01cb83776d9501c33e8492 should address that. It's in a separate branch for now (https://github.com/alexarchambault/argonaut-shapeless/tree/topic/variedencodings), but I'll merge it as soon as shapeless 2.2 final is out.

Btw, the problem was more `tail` than `head` in the lines you're referencing. The problem was that although the codec for `Option` (in argonaut) was changing the cursor from failed to success (assuming failed means a `None`), we were still going on with decoding the tail with the failed cursor - and the tail decoder had no reason to change it from failed to success.
